<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.1.1" />
      <PackageReference Include="Hangfire" Version="1.8.23" />
      <PackageReference Include="Hangfire.NetCore" Version="1.8.23" />
      <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Services\Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\images\products\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\PriceRu\Index.cshtml" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\b.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\dir.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\fb.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\gmail.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\google.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\in.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\inst.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\phone.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\pin.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\snap.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\spot.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\tg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\tt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\vk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\wsup.png" />
      <_ContentIncludedByDefault Remove="wwwroot\social network\yt.png" />
    </ItemGroup>

    <ItemGroup>
      <None Include="wwwroot\data\PDB.html" />
    </ItemGroup>

</Project>
